Feature/df generator/speak leash to df
speakleash/speakleash-examples pull request #13
Opened 2023-07-26 22:01 UTC by przemekboruta

Resolves #4

2023-08-06 18:12 UTC, IgorTest19 requested changes

2023-08-06 18:12 UTC, IgorTest19 commented on example_4_pandas/charts.py
> +# Generate .html charts from the dataset
For module docstrig, the text should be contained in triple brackets, like::
`"""Generate .html charts from the dataset"""`

2023-08-06 18:12 UTC, IgorTest19 commented on example_4_pandas/charts.py
> +save_path = "imgs/"
Constant names could be written in UPPER_CASE naming style:
`SAVE_PATH = "imgs/"`

2023-08-06 18:12 UTC, IgorTest19 commented on example_4_pandas/charts.py
> +class Chart:
Descriptions (docstrings) should be added to the class and methods.

2023-08-06 20:20 UTC, Samox1 commented
Only suggestion - for clarity, leave only the example of loading data into a pandas DataFrame and making a separate folder for the demonstration of charts from charts.py

2023-08-07 12:13 UTC, IgorTest19 commented
> The only suggestion - for clarity, leave only the example of loading data into pandas DataFrame and create a separate folder for demonstrating charts with charts.py.

This is a good suggestion, but in order not to make things too complicated, we can leave both main.py and charts.py files in one directory and create a short explanation in the readme.md file with the purpose/usage of both files. This pull request was created for the issue:
[SpeakLeash and pandas #4](https://github.com/speakleash/speakleash-examples/issues/4)
which was about creating a data frame based on Speakleash data. More complex examples should be done in another issue, as this issue resolves a fairly basic case.

2023-08-16 21:00 UTC, IgorTest19 commented on example_4_pandas/charts.py
> +import os
Add module docstring (short description)

2023-10-18 21:21 UTC, IgorTest19 approved these changes

2023-10-18 21:21 UTC, IgorTest19 commented on example_4_pandas/main.py
> +def get_reader(project_name: str, speakleash_class: Speakleash) -> Reader.stream_data:
add short descriptions to these functions

2023-10-18 21:21 UTC, IgorTest19 commented on example_4_pandas/main.py
> +def get_reader(project_name: str, speakleash_class: Speakleash) -> Reader.stream_data:
Done

2023-10-18 21:21 UTC, IgorTest19 commented on example_4_pandas/charts.py
> +import os
Done

2023-10-18 21:34 UTC, IgorTest19 approved these changes

2023-10-18 21:35 UTC, merged