Add extraction of high-quality docs to text files
speakleash/speakleash-examples pull request #17
Opened 2023-08-06 18:39 UTC by MarekGarbowski

This commit introduces a new function save_high_quality_docs() in the extraction_to_txt_file.py. It saves high-quality documents from the Speakleash dataset to a specified folder, creating the necessary directories if they don't exist. The .gitignore file has been updated to exclude the output directory from the repository. This function helps in segregating high quality documents for further analysis.

2023-08-11 13:37 UTC, IgorTest19 requested changes

2023-08-11 13:37 UTC, IgorTest19 commented on example_3_quality_metrics/extraction_to_txt_file.py
> +import os
Missing module docstring.

2023-08-11 13:37 UTC, IgorTest19 commented on example_3_quality_metrics/extraction_to_txt_file.py
> +def save_high_quality_docs(txt_folder_name):
You can split up functionalities using 2 functions:
- `def get_datatxt_folder_name)` which creates directory
- `def save_quality_docs(quality='HIGH')` which will wrap code from creating an instance of the Speakleash class (from line 26 to 41)
- use these two functions inside of condition:` if __name__ == '__main__':`

Look at the following example:
https://github.com/speakleash/speakleash-examples/pull/13/files (file charts.py)

2023-08-11 13:37 UTC, IgorTest19 commented on .gitignore
>  #  be found at https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore
Remove .gitignore file. It's not needed there :)

2023-08-27 19:38 UTC, MarekGarbowski commented
The extraction_to_txt_file script has been revised for added versatility. A new module has been added providing functions to create necessary directories and save documents from the 'speakleash' dataset to a specific folder. The 'save_high_quality_docs' method was updated to 'save_quality_docs' to allow for selection of document quality. New usage information was also added for guidance on the script modification, importing and using the module's functions, running the script directly, and the output from the script execution. A 'get_data' function was also added to manage the creation of necessary directories. This update provides improved script functionality and versatile document retrieval.

2023-09-03 11:29 UTC, IgorTest19 approved these changes

2023-09-03 17:26 UTC, MarekGarbowski commented
Added README.md file and both moved to separate folder.

2023-09-03 19:49 UTC, MarekGarbowski commented
Modified the readme.md and main files as suggested.

2023-09-03 19:52 UTC, IgorTest19 approved these changes

2023-09-03 19:52 UTC, merged